# Generated by Django 5.1.1 on 2025-12-15 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAiCourseUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rpl_id', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=255)),
                ('designation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.territory')),
            ],
            options={
                'verbose_name': 'Doctors AI Course Up',
                'verbose_name_plural': 'Doctors AI Courses Up',
                'db_table': 'doctors_ai_course_up',
            },
        ),
    ]
