# Generated by Django 5.2.4 on 2026-06-07 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftVoucherCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_id', models.CharField(max_length=20, unique=True)),
                ('dr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gift', models.CharField(choices=[('Apex', 'Apex'), ('Bata', 'Bata'), ('Infinity', 'Infinity'), ('Aarong', 'Aarong')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_voucher_catalogs_26', to='core.territory')),
            ],
            options={
                'verbose_name': 'Doctor Gift Voucher Catalog 26',
                'verbose_name_plural': 'Doctor Gift Voucher Catalogs 26',
                'db_table': 'gift_voucher_catalogs_26',
            },
        ),
    ]
