# Generated by Django 5.1.1 on 2025-12-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_id', models.CharField(max_length=20, unique=True)),
                ('dr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('plants', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.territory')),
            ],
            options={
                'verbose_name': 'Plant Module',
                'verbose_name_plural': 'Plant Module',
                'db_table': 'plant_module',
            },
        ),
    ]
