# Generated by Django 5.2.4 on 2026-02-28 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PohelaBoishakhCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_id', models.CharField(max_length=20, unique=True)),
                ('dr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(choices=[('SM/38', 'Sm'), ('L/40', 'L'), ('XL/42', 'Xl'), ('XXL/44', 'Xxl'), ('XXXL/46', 'Xxxl')], default='L/40', max_length=20)),
                ('gifts', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.territory')),
            ],
            options={
                'verbose_name': 'Pohela Boishakh Catalog',
                'verbose_name_plural': 'Pohela Boishakh Catalogs',
                'db_table': 'pohela_boishakh_catalogs',
            },
        ),
    ]
