# Generated by Django 5.2.4 on 2026-03-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_boishakh_catalog', '0002_alter_pohelaboishakhcatalog_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pohelaboishakhcatalog',
            name='size',
            field=models.CharField(choices=[('S/38', 'S'), ('M/40', 'M'), ('L/42', 'L'), ('XL/44', 'Xl'), ('XXL/46', 'Xxl'), ('XXXL/48', 'Xxxl')], default='L/42', max_length=20),
        ),
    ]
