# Generated by Django 5.2.4 on 2026-06-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NfcCardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_rpl_id', models.CharField(max_length=10, unique=True)),
                ('dr_name', models.CharField(max_length=155)),
                ('degree', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('institute', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NFC Card Info',
                'verbose_name_plural': 'NFC Card Infos',
                'db_table': 'nfc_card_info',
            },
        ),
    ]
