# Generated by Django 5.2.4 on 2026-06-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        ('nfc_card_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfccardinfo',
            name='territory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.territory'),
            preserve_default=False,
        ),
    ]
