# Generated by Django 5.2.4 on 2026-06-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc_card_info', '0002_nfccardinfo_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfccardinfo',
            name='designation',
            field=models.CharField(default='', max_length=155),
            preserve_default=False,
        ),
    ]
