# Generated by Django 5.2.4 on 2026-01-21 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_id', models.CharField(max_length=20, unique=True)),
                ('dr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gift', models.CharField(choices=[('Araong gift card', 'araong gift card'), ('Mega Mall gift card', 'Mega Mall gift card'), ('Watch', 'Watch')], default='Araong gift card', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.territory')),
            ],
            options={
                'verbose_name': 'Doctor Develop 1Q26',
                'verbose_name_plural': 'Doctors Develop 1Q26',
                'db_table': 'doctor_development',
            },
        ),
    ]
