# Generated by Django 5.2.4 on 2026-01-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_development', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordevelopment',
            name='gift',
            field=models.CharField(choices=[('Araong gift card', 'araong gift card'), ('Mega Mall gift card', 'Mega Mall gift card'), ('Watch', 'Watch'), ('Kiam 7pcs set', 'Kiam 7pcs set')], default='Araong gift card', max_length=100),
        ),
    ]
