# Generated by Django 5.2.4 on 2026-04-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_data', '0002_rename_designation_doctor_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='visiting_days',
            field=models.TextField(blank=True, null=True),
        ),
    ]
