# Generated by Django 5.2.4 on 2026-04-06 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCatalog2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_id', models.CharField(max_length=20, unique=True)),
                ('dr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gift', models.CharField(choices=[('President Trolley Bag- 9595', 'President Trolley Bag- 9595'), ('Philips 1000 Series 4.2 Liter Air Fryer', 'Philips 1000 Series 4.2 Liter Air Fryer'), ('Aarong Gift Voucher', 'Aarong Gift Voucher'), ('Infinity Gift Voucher', 'Infinity Gift Voucher'), ('Apex Gift Voucher', 'Apex Gift Voucher'), ('Kiam Induction cooker (H-22) & 4Pc Cookware Combo', 'Kiam Induction cooker (H-22) & 4Pc Cookware Combo')], default='President Trolley Bag- 9595', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_catalogs_2', to='core.territory')),
            ],
            options={
                'verbose_name': 'Doctor Gift Catalog 2',
                'verbose_name_plural': 'Doctor Gift Catalogs 2',
                'db_table': 'gift_catalogs_2',
            },
        ),
    ]
